# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 14:06
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commande', '0004_auto_20170927_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('prixTotal', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('prix', models.FloatField()),
                ('stock', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='boisson',
            name='commandeTotal',
        ),
        migrations.RemoveField(
            model_name='nourriture',
            name='commandeTotal',
        ),
        migrations.DeleteModel(
            name='Stuff',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='commandeTotal',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='solde',
        ),
        migrations.AddField(
            model_name='participant',
            name='soldes',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Boisson',
        ),
        migrations.DeleteModel(
            name='CommandeTotal',
        ),
        migrations.DeleteModel(
            name='Nourriture',
        ),
        migrations.AddField(
            model_name='evenement',
            name='participants',
            field=models.ManyToManyField(to='commande.Participant'),
        ),
        migrations.AddField(
            model_name='commande',
            name='prod',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='commande.Produit'),
        ),
    ]
