# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0006_produit_typep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='typeP',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
